# Generated by Django 4.1.4 on 2023-01-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='checkout',
            field=models.DateTimeField(null=True),
        ),
    ]
