# Generated by Django 4.1.4 on 2023-01-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_attendance_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='available_time',
            field=models.DateTimeField(null=True),
        ),
    ]
