# Generated by Django 4.0.4 on 2023-01-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_attendance_available_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='available_time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
